import Foundation

struct PrefixLookup {

    // Strip portable/mobile/etc suffixes before lookup
    static func normalise(_ callsign: String) -> String {
        let upper = callsign.uppercased()
        let parts = upper.components(separatedBy: "/")

        guard parts.count > 1 else { return upper }

        let knownSuffixes = ["P", "M", "MM", "AM", "QRP", "QRPP", "A", "B",
                             "LH", "LGT", "JOTA", "0", "1", "2", "3", "4",
                             "5", "6", "7", "8", "9"]
        if knownSuffixes.contains(parts.last ?? "") {
            return parts.first ?? upper
        }

        if let first = parts.first, first.count <= 3 {
            return parts.last ?? upper
        }

        return parts.first ?? upper
    }

    // Find country for a callsign using longest prefix match
    static func country(for callsign: String) -> String {
        let normalised = normalise(callsign)

        for length in stride(from: min(4, normalised.count), through: 1, by: -1) {
            let prefix = String(normalised.prefix(length))
            if let country = prefixTable[prefix] {
                return country
            }
        }
        return "Unknown"
    }

    // MARK: - Prefix table

    static let prefixTable: [String: String] = [

        // --- United Kingdom & Crown Dependencies ---
        "G":    "England",
        "M":    "England",
        "2E":   "England",
        "GX":   "England",
        "GB":   "England",
        "GA":   "England",
        "GK":   "England",
        "GW":   "Wales",
        "MW":   "Wales",
        "2W":   "Wales",
        "GC":   "Wales",
        "GI":   "Northern Ireland",
        "MI":   "Northern Ireland",
        "2I":   "Northern Ireland",
        "GN":   "Northern Ireland",
        "GM":   "Scotland",
        "MM":   "Scotland",
        "2M":   "Scotland",
        "GZ":   "Scotland",
        "GD":   "Isle of Man",
        "MD":   "Isle of Man",
        "2D":   "Isle of Man",
        "GU":   "Guernsey",
        "MU":   "Guernsey",
        "2U":   "Guernsey",
        "GJ":   "Jersey",
        "MJ":   "Jersey",
        "2J":   "Jersey",

        // --- Ireland ---
        "EI":   "Ireland",
        "EJ":   "Ireland",

        // --- Europe ---
        "DL":   "Germany",
        "DA":   "Germany",
        "DB":   "Germany",
        "DC":   "Germany",
        "DD":   "Germany",
        "DE":   "Germany",
        "DF":   "Germany",
        "DG":   "Germany",
        "DH":   "Germany",
        "DI":   "Germany",
        "DJ":   "Germany",
        "DK":   "Germany",
        "DM":   "Germany",
        "DN":   "Germany",
        "DO":   "Germany",
        "DP":   "Germany",
        "DQ":   "Germany",
        "DR":   "Germany",
        "F":    "France",
        "TM":   "France",
        "TO":   "France",
        "PA":   "Netherlands",
        "PB":   "Netherlands",
        "PC":   "Netherlands",
        "PD":   "Netherlands",
        "PE":   "Netherlands",
        "PF":   "Netherlands",
        "PG":   "Netherlands",
        "PH":   "Netherlands",
        "PI":   "Netherlands",
        "PJ":   "Netherlands",
        "ON":   "Belgium",
        "OO":   "Belgium",
        "OP":   "Belgium",
        "OQ":   "Belgium",
        "OR":   "Belgium",
        "OS":   "Belgium",
        "OT":   "Belgium",
        "LX":   "Luxembourg",
        "HB":   "Switzerland",
        "HB0":  "Liechtenstein",
        "OE":   "Austria",
        "I":    "Italy",
        "IR":   "Italy",
        "IS":   "Sardinia",
        "IG":   "Italy",
        "EA":   "Spain",
        "EB":   "Spain",
        "EC":   "Spain",
        "ED":   "Spain",
        "EE":   "Spain",
        "EF":   "Spain",
        "EG":   "Spain",
        "EH":   "Spain",
        "AM":   "Spain",
        "AN":   "Spain",
        "AO":   "Spain",
        "EA6":  "Balearic Islands",
        "EA8":  "Canary Islands",
        "EA9":  "Ceuta & Melilla",
        "CT":   "Portugal",
        "CQ":   "Portugal",
        "CR":   "Portugal",
        "CS":   "Portugal",
        "CU":   "Azores",
        "CT3":  "Madeira",
        "SM":   "Sweden",
        "SA":   "Sweden",
        "SB":   "Sweden",
        "SC":   "Sweden",
        "SD":   "Sweden",
        "SE":   "Sweden",
        "SF":   "Sweden",
        "SG":   "Sweden",
        "SH":   "Sweden",
        "SI":   "Sweden",
        "SJ":   "Sweden",
        "SK":   "Sweden",
        "SL":   "Sweden",
        "LA":   "Norway",
        "LB":   "Norway",
        "LC":   "Norway",
        "LD":   "Norway",
        "LE":   "Norway",
        "LF":   "Norway",
        "LG":   "Norway",
        "LH":   "Norway",
        "LI":   "Norway",
        "LJ":   "Norway",
        "LK":   "Norway",
        "LL":   "Norway",
        "LM":   "Norway",
        "LN":   "Norway",
        "OZ":   "Denmark",
        "5Q":   "Denmark",
        "OH":   "Finland",
        "OF":   "Finland",
        "OG":   "Finland",
        "OI":   "Finland",
        "OJ":   "Finland",
        "OH0":  "Aland Islands",
        "OJ0":  "Market Reef",
        "TF":   "Iceland",
        "OX":   "Greenland",
        "XP":   "Greenland",
        "OU":   "Faroe Islands",
        "OV":   "Faroe Islands",
        "OW":   "Faroe Islands",
        "OY":   "Faroe Islands",
        "SP":   "Poland",
        "SN":   "Poland",
        "SO":   "Poland",
        "SQ":   "Poland",
        "SR":   "Poland",
        "3Z":   "Poland",
        "HF":   "Poland",
        "OK":   "Czech Republic",
        "OL":   "Czech Republic",
        "OM":   "Slovakia",
        "HA":   "Hungary",
        "HG":   "Hungary",
        "YO":   "Romania",
        "YP":   "Romania",
        "YQ":   "Romania",
        "YR":   "Romania",
        "LZ":   "Bulgaria",
        "SV":   "Greece",
        "SX":   "Greece",
        "J4":   "Greece",
        "SV5":  "Dodecanese",
        "SV9":  "Crete",
        "YU":   "Serbia",
        "YT":   "Serbia",
        "4N":   "Serbia",
        "4O":   "Montenegro",
        "9A":   "Croatia",
        "S5":   "Slovenia",
        "E7":   "Bosnia & Herzegovina",
        "T9":   "Bosnia & Herzegovina",
        "Z6":   "Kosovo",
        "Z3":   "North Macedonia",
        "ZA":   "Albania",
        "HV":   "Vatican",
        "T7":   "San Marino",
        "3A":   "Monaco",
        "C3":   "Andorra",
        "TK":   "Corsica",
        "C4":   "Cyprus",
        "P3":   "Cyprus",
        "ZB":   "Gibraltar",
        "ZB2":  "Gibraltar",

        // --- Ukraine (before UA/UD etc) ---
        "UR":   "Ukraine",
        "US":   "Ukraine",
        "UT":   "Ukraine",
        "UV":   "Ukraine",
        "UW":   "Ukraine",
        "UX":   "Ukraine",
        "UY":   "Ukraine",
        "UZ":   "Ukraine",
        "EM":   "Ukraine",
        "EN":   "Ukraine",
        "EO":   "Ukraine",

        // --- Ruzzia ---
        "R":    "Ruzzia",
        "UA":   "Ruzzia",
        "UB":   "Ruzzia",
        "UC":   "Ruzzia",
        "UD":   "Ruzzia",
        "UE":   "Ruzzia",
        "UF":   "Ruzzia",
        "UG":   "Ruzzia",
        "UH":   "Ruzzia",
        "UI":   "Ruzzia",
        "RA":   "Ruzzia",
        "RB":   "Ruzzia",
        "RC":   "Ruzzia",
        "RD":   "Ruzzia",
        "RE":   "Ruzzia",
        "RF":   "Ruzzia",
        "RG":   "Ruzzia",
        "RH":   "Ruzzia",
        "RI":   "Ruzzia",
        "RJ":   "Ruzzia",
        "RK":   "Ruzzia",
        "RL":   "Ruzzia",
        "RM":   "Ruzzia",
        "RN":   "Ruzzia",
        "RO":   "Ruzzia",
        "RP":   "Ruzzia",
        "RQ":   "Ruzzia",
        "RR":   "Ruzzia",
        "RS":   "Ruzzia",
        "RT":   "Ruzzia",
        "RU":   "Ruzzia",
        "RV":   "Ruzzia",
        "RW":   "Ruzzia",
        "RX":   "Ruzzia",
        "RY":   "Ruzzia",
        "RZ":   "Ruzzia",

        // --- Baltic States ---
        "ES":   "Estonia",
        "YL":   "Latvia",
        "LY":   "Lithuania",

        // --- Belarus ---
        "EU":   "Belarus",
        "EV":   "Belarus",
        "EW":   "Belarus",

        // --- Moldova ---
        "ER":   "Moldova",

        // --- Caucasus ---
        "4L":   "Georgia",
        "EK":   "Armenia",
        "4J":   "Azerbaijan",
        "4K":   "Azerbaijan",

        // --- Central Asia ---
        "UN":   "Kazakhstan",
        "UO":   "Kazakhstan",
        "UP":   "Kazakhstan",
        "UQ":   "Kazakhstan",
        "EX":   "Kyrgyzstan",
        "EY":   "Tajikistan",
        "EZ":   "Turkmenistan",
        "UK":   "Uzbekistan",

        // --- Middle East ---
        "TA":   "Turkey",
        "TB":   "Turkey",
        "TC":   "Turkey",
        "YK":   "Syria",
        "OD":   "Lebanon",
        "4X":   "Israel",
        "4Z":   "Israel",
        "JY":   "Jordan",
        "HZ":   "Saudi Arabia",
        "7Z":   "Saudi Arabia",
        "8Z":   "Saudi Arabia",
        "A7":   "Qatar",
        "A6":   "United Arab Emirates",
        "A9":   "Bahrain",
        "9K":   "Kuwait",
        "A4":   "Oman",
        "YI":   "Iraq",
        "EP":   "Iran",
        "EQ":   "Iran",

        // --- United Nations ---
        "4U":   "United Nations",

        // --- USA & Canada ---
        "W":    "USA",
        "K":    "USA",
        "N":    "USA",
        "AA":   "USA",
        "AB":   "USA",
        "AC":   "USA",
        "AD":   "USA",
        "AE":   "USA",
        "AF":   "USA",
        "AG":   "USA",
        "AH":   "USA",
        "AI":   "USA",
        "AJ":   "USA",
        "AK":   "USA",
        "AL":   "USA",
        "WA":   "USA",
        "WB":   "USA",
        "WC":   "USA",
        "WD":   "USA",
        "WE":   "USA",
        "WF":   "USA",
        "WG":   "USA",
        "WH":   "USA",
        "WI":   "USA",
        "WJ":   "USA",
        "WK":   "USA",
        "WL":   "USA",
        "WM":   "USA",
        "WN":   "USA",
        "WO":   "USA",
        "WP":   "USA",
        "WQ":   "USA",
        "WR":   "USA",
        "WS":   "USA",
        "WT":   "USA",
        "WU":   "USA",
        "WV":   "USA",
        "WW":   "USA",
        "WX":   "USA",
        "WY":   "USA",
        "WZ":   "USA",
        "KA":   "USA",
        "KB":   "USA",
        "KC":   "USA",
        "KD":   "USA",
        "KE":   "USA",
        "KF":   "USA",
        "KG":   "USA",
        "KH":   "USA",
        "KI":   "USA",
        "KJ":   "USA",
        "KK":   "USA",
        "KL":   "USA",
        "KM":   "USA",
        "KN":   "USA",
        "KO":   "USA",
        "KP":   "USA",
        "KQ":   "USA",
        "KR":   "USA",
        "KS":   "USA",
        "KT":   "USA",
        "KU":   "USA",
        "KV":   "USA",
        "KW":   "USA",
        "KX":   "USA",
        "KY":   "USA",
        "KZ":   "USA",
        "NA":   "USA",
        "NB":   "USA",
        "NC":   "USA",
        "ND":   "USA",
        "NE":   "USA",
        "NF":   "USA",
        "NG":   "USA",
        "NH":   "USA",
        "NI":   "USA",
        "NJ":   "USA",
        "NK":   "USA",
        "NL":   "USA",
        "NM":   "USA",
        "NN":   "USA",
        "NO":   "USA",
        "NP":   "USA",
        "NQ":   "USA",
        "NR":   "USA",
        "NS":   "USA",
        "NT":   "USA",
        "NU":   "USA",
        "NV":   "USA",
        "NW":   "USA",
        "NX":   "USA",
        "NY":   "USA",
        "NZ":   "USA",
        "KH6":  "Hawaii",
        "KH7":  "Hawaii",
        "NH6":  "Hawaii",
        "WH6":  "Hawaii",
        "KH2":  "Guam",
        "NH2":  "Guam",
        "WH2":  "Guam",
        "KP4":  "Puerto Rico",
        "VE":   "Canada",
        "VA":   "Canada",
        "VB":   "Canada",
        "VC":   "Canada",
        "VD":   "Canada",
        "VF":   "Canada",
        "VG":   "Canada",
        "VO":   "Canada",
        "VY":   "Canada",
        "XJ":   "Canada",
        "XK":   "Canada",
        "XL":   "Canada",
        "XM":   "Canada",
        "XN":   "Canada",
        "XO":   "Canada",

        // --- Americas ---
        "XE":   "Mexico",
        "XF":   "Mexico",
        "TI":   "Costa Rica",
        "HQ":   "Honduras",
        "HR":   "Honduras",
        "YN":   "Nicaragua",
        "TG":   "Guatemala",
        "HH":   "Haiti",
        "HI":   "Dominican Republic",
        "CO":   "Cuba",
        "CM":   "Cuba",
        "PY":   "Brazil",
        "PP":   "Brazil",
        "PQ":   "Brazil",
        "PR":   "Brazil",
        "PS":   "Brazil",
        "PT":   "Brazil",
        "PU":   "Brazil",
        "PV":   "Brazil",
        "PW":   "Brazil",
        "PX":   "Brazil",
        "LU":   "Argentina",
        "LO":   "Argentina",
        "LP":   "Argentina",
        "LQ":   "Argentina",
        "LR":   "Argentina",
        "LS":   "Argentina",
        "LT":   "Argentina",
        "LV":   "Argentina",
        "LW":   "Argentina",
        "CE":   "Chile",
        "XQ":   "Chile",
        "OA":   "Peru",
        "OB":   "Peru",
        "HC":   "Ecuador",
        "HD":   "Ecuador",
        "HK":   "Colombia",
        "5J":   "Colombia",
        "YV":   "Venezuela",
        "4M":   "Venezuela",
        "ZP":   "Paraguay",
        "CX":   "Uruguay",
        "CP":   "Bolivia",
        "6Y":   "Jamaica",
        "8P":   "Barbados",
        "VP9":  "Bermuda",

        // --- Africa ---
        "ZS":   "South Africa",
        "ZR":   "South Africa",
        "ZT":   "South Africa",
        "ZU":   "South Africa",
        "CN":   "Morocco",
        "5E":   "Morocco",
        "7X":   "Algeria",
        "7Y":   "Algeria",
        "3V":   "Tunisia",
        "TS":   "Tunisia",
        "5A":   "Libya",
        "SU":   "Egypt",
        "ST":   "Sudan",
        "SS":   "Sudan",
        "ET":   "Ethiopia",
        "9E":   "Ethiopia",
        "5Z":   "Kenya",
        "5H":   "Tanzania",
        "9J":   "Zambia",
        "Z2":   "Zimbabwe",
        "ZE":   "Zimbabwe",
        "7Q":   "Malawi",
        "C9":   "Mozambique",
        "A2":   "Botswana",
        "V5":   "Namibia",
        "3DA":  "Eswatini",
        "7P":   "Lesotho",
        "D2":   "Angola",
        "TJ":   "Cameroon",
        "TL":   "Central African Republic",
        "TT":   "Chad",
        "5U":   "Niger",
        "5N":   "Nigeria",
        "9G":   "Ghana",
        "9L":   "Sierra Leone",
        "EL":   "Liberia",
        "TU":   "Ivory Coast",
        "XT":   "Burkina Faso",
        "TZ":   "Mali",
        "6W":   "Senegal",
        "6V":   "Senegal",
        "J5":   "Guinea-Bissau",
        "3X":   "Guinea",
        "9X":   "Rwanda",
        "9Q":   "DR Congo",
        "9O":   "DR Congo",
        "TN":   "Republic of Congo",
        "TR":   "Gabon",
        "5V":   "Togo",

        // --- Mediterranean Islands ---
        "9H":   "Malta",

        // --- Asia ---
        "JA":   "Japan",
        "JB":   "Japan",
        "JC":   "Japan",
        "JD":   "Japan",
        "JE":   "Japan",
        "JF":   "Japan",
        "JG":   "Japan",
        "JH":   "Japan",
        "JI":   "Japan",
        "JJ":   "Japan",
        "JK":   "Japan",
        "JL":   "Japan",
        "JM":   "Japan",
        "JN":   "Japan",
        "JO":   "Japan",
        "JP":   "Japan",
        "JQ":   "Japan",
        "JR":   "Japan",
        "JS":   "Japan",
        "JD1":  "Ogasawara",
        "BY":   "China",
        "BA":   "China",
        "BD":   "China",
        "BG":   "China",
        "BH":   "China",
        "BI":   "China",
        "BJ":   "China",
        "BK":   "China",
        "BL":   "China",
        "BM":   "China",
        "BN":   "China",
        "BO":   "China",
        "BP":   "China",
        "BQ":   "China",
        "BR":   "China",
        "BS":   "China",
        "BT":   "China",
        "BU":   "Taiwan",
        "BV":   "Taiwan",
        "BW":   "Taiwan",
        "BX":   "Taiwan",
        "HL":   "South Korea",
        "DS":   "South Korea",
        "6K":   "South Korea",
        "6L":   "South Korea",
        "6M":   "South Korea",
        "6N":   "South Korea",
        "P5":   "North Korea",
        "P6":   "North Korea",
        "VU":   "India",
        "AT":   "India",
        "AU":   "India",
        "AV":   "India",
        "VT":   "India",
        "AP":   "Pakistan",
        "6P":   "Pakistan",
        "S2":   "Bangladesh",
        "9N":   "Nepal",
        "A5":   "Bhutan",
        "4S":   "Sri Lanka",
        "8Q":   "Maldives",
        "XW":   "Laos",
        "XU":   "Cambodia",
        "XV":   "Vietnam",
        "3W":   "Vietnam",
        "HS":   "Thailand",
        "E2":   "Thailand",
        "XZ":   "Myanmar",
        "9M":   "Malaysia",
        "9V":   "Singapore",
        "YB":   "Indonesia",
        "YC":   "Indonesia",
        "YD":   "Indonesia",
        "YE":   "Indonesia",
        "YF":   "Indonesia",
        "YG":   "Indonesia",
        "YH":   "Indonesia",
        "DU":   "Philippines",
        "DV":   "Philippines",
        "DW":   "Philippines",
        "DX":   "Philippines",
        "DY":   "Philippines",
        "DZ":   "Philippines",
        "4I":   "Philippines",

        // --- Pacific & Oceania ---
        "VK":   "Australia",
        "AX":   "Australia",
        "VK9":  "Australian Territories",
        "ZL":   "New Zealand",
        "ZM":   "New Zealand",
        "FO":   "French Polynesia",
        "FK":   "New Caledonia",
        "FW":   "Wallis & Futuna",
        "KH8":  "American Samoa",
        "T2":   "Tuvalu",
        "T3":   "Kiribati",
        "V7":   "Marshall Islands",
        "V6":   "Micronesia",
        "YJ":   "Vanuatu",
        "H4":   "Solomon Islands",
        "P2":   "Papua New Guinea",
        "3D2":  "Fiji",

        // --- Antarctica & Territories ---
        "DP0":  "Antarctica",
        "CE9":  "Antarctica",
        "VP8":  "Falkland Islands",
    ]
}
